image: archlinux/base:latest

before_script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm --needed -S gcc make mesa opencl-mesa ocl-icd opencl-headers libx11 glfw-x11 glew

stages:
    - build

gcc:
    stage: build
    script:
    - export CC=gcc
    - make -j$(nproc)
