image :archlinux/base:latest

before_script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm --needed -S gcc clang make mesa opencl-mesa ocl-icd opencl-headers

stages:
    - build

gcc:
    stage: build
    script:
    - export CC=gcc
    - make -j$(nproc)

clang:
    stage: build
    script:
    - export CC=clang
    - make -j$(nproc)
